### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Slinky142** [cloudnode-pro/BankAccounts#136]
hi this is my new account my other one was called lemonvace I did the German translation for you last year with the BankAccounts plugin and wanted to ask if there are anything else I can do for the plugin? Because the plugin is really great and I would like to help too, so are there things I could do?

**Comment by Slinky142** [comment]
I would even like to program, I would just need to teach myself a bit better, but I would like to help you with everything that comes up, so what kind of things could I do?

**Comment by Slinky142** [comment]
?

**Comment by zefir-git** [comment]
Hi! I am glad you like the plugin and thanks for your interest in contributing.

Do you have experience with Java?

If you have a Matrix account, please contact me at `zefir:cloudnode.pro` to discuss further

**Comment by Slinky142** [comment]
I wrote you

**Comment by Slinky142** [comment]
on SchildiChat

**Comment by Slinky142** [comment]
is this ok?

**Comment by Slinky142** [comment]
username is there: @slinkylemon155:matrix.org
display name: Slinky

**Comment by Slinky142** [comment]
hello?

**Comment by zefir-git** [comment]
closing this since we got in touch on matrix
