### ISSUE TITLE
Transfer funds to/from EssentialsX

### ISSUE THREAD

**Issue by Slinky142** [cloudnode-pro/BankAccounts#138]
hi I have a new function: if you have vault set to false in the config and you can e.g. essentialsX allows you to transfer a certain amount of money from your bank account to your essentialsX account and of course it would be nice if you could do it from essentialsX to your bank account

**Comment by Slinky142** [comment]
?

**Comment by zefir-git** [comment]
I don't think that would be possible. Vault is normally the economy interface between plugins.

If you have admin permissions, you can transfer money by manipulating the BankAccounts and Essentials balances:
 - `/bank setbal <account> <new balance>`
 - `/eco <give|take> <player> <amount>`

**Comment by Slinky142** [comment]
Ok, but I find it a bit more complicated because I want to use essentialsX as a normal money system and then a bank plugin like this and you should then be able to transfer money from essentialsX to your bank. That would perhaps even be better since I use the vault system I'm a bit overwhelmed by the BankAccountts plugin or don't really understand it, so maybe it would be possible after all?
