### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by lemonvace** [cloudnode-pro/BankAccounts#29]
Ok, now it's a very awesome plugin. I would have a suggestion that you can download the plugin in German or that there is a folder called lang in the BankAccounts folder and in it is for example the lang-de.yml where everything is in German and you can set it in the plugin configuration which language you want.

**Comment by zefir-git** [comment]
You can edit all messages in the config, so you can translate them to German or any language if you want.

I can add configs with translated messages in the Wiki. If you are a native German speaker or know German well, your help in translating would be greatly appreciated weil mein Deutsch gar nicht so gut ist.

**Comment by lemonvace** [comment]
ok yes i can help him

**Comment by lemonvace** [comment]
can you send me a file where all the messages are listed one below the other? which I can then translate then I will send you the translated file back to you

**Comment by zefir-git** [comment]
> can you send me a file where all the messages are listed one below the other? which I can then translate then I will send you the translated file back to you

You can find them in `BankAccounts/config.yml` under the messages section. Here is the default config on the current version:

https://github.com/cloudnode-pro/BankAccounts/blob/03719f5d9f5ef8acd514eeca1e1de710ae31caff/src/main/resources/config.yml#L225-L420

**Comment by lemonvace** [comment]
ok something like the <red>(!) and the <click:suggest_command: I don't have to translate it, do I?

**Comment by zefir-git** [comment]
Yeah, don't translate that.

**Comment by lemonvace** [comment]
ok do you want to translate everything you sent me?

**Comment by zefir-git** [comment]
Feel free to

**Comment by lemonvace** [comment]
ok i will start now

**Comment by lemonvace** [comment]
ok

**Comment by lemonvace** [comment]
so I'm done

**Comment by zefir-git** [comment]
I have added your translation to the Wiki here: https://github.com/cloudnode-pro/BankAccounts/wiki/Translations

I reviewed it and made some changes. If you see any mistakes, please let me know. Otherwise feel free to close this issue.
