### ISSUE TITLE
Vault API

### ISSUE THREAD

**Issue by lemonvace** [cloudnode-pro/BankAccounts#34]
I have a suggestion that suggests the Personal and Business options. You can choose an option for a vault account (such as a checking account or similar). This account type would be limited to 1 per player as other plugins cannot work with multiple accounts per player.

**Comment by km127pl** [comment]
*a bit of a late response*
The idea now is to have an account marked as the `default` account (name may change), and it will be used as the account to interface with Vault API, as of right now this is not yet implemented.

Some command like `account <id> default true` would mark an account as the `default` one, you could of course have only one account marked as default as that's how Vault works.

**Comment by zefir-git** [comment]
Supersedes #5
