### ISSUE TITLE
PlaceholderAPI integration

### ISSUE THREAD

**Issue by krqte1mirapo** [cloudnode-pro/BankAccounts#43]
Please add placeholder <3

**Comment by zefir-git** [comment]
Thank you for the suggestion. What kind of placeholders would you like to see?

**Comment by krqte1mirapo** [comment]
%bankaccound_balance_name% %bankaccount_transaction%. And add bank menu. If you create a new card, it will appear in the bank menu in the “My Accounts” item. For example, I have one account and in the “My Accounts” menu there will be only one head (It can be customized), I create another account and another head appears. It would be very cool if you implemented this.

**Comment by krqte1mirapo** [comment]
If I could get your discord I would send you an example of all this.

**Comment by zefir-git** [comment]
Sure, my Discord is `zefir23`.

**Comment by zefir-git** [comment]
Were you able to find me? Also feel free to post anything here

**Comment by krqte1mirapo** [comment]
Yeah, i wait accept =)

**Comment by zefir-git** [comment]
We discussed on Discord the format of the placeholders and agreed on something like <code>%bankaccounts_balance_<i>accountId</i>%</code>
