### ISSUE TITLE
Invoicing

### ISSUE THREAD

**Issue by WoofWolfGG** [cloudnode-pro/BankAccounts#68]
It would be cool if players with special permission could invoice other players. 
Example: `/bank createinvoice [targetplayer] [amount] [account where this invoice should go] [comment]`.
After that, when a player joins into the server, a notification will pop up that he has an unpaid invoice. You can view your invoices with the command `/bank invoices` for example. This way it would be very cool to issue penalties on RP servers.

**Comment by zefir-git** [comment]
Hi! For payment terminal, you should take a look at the [POS](https://github.com/cloudnode-pro/BankAccounts/wiki/POS) feature.

For ATMs, do you mean a location where players can exchange their bank balance for an item (e.g. diamond ore)? If that's the case, we are currently working on #34 which will allow integration with third-party plugins like chest shops that can be set up to trade currency for items between players or even with admin shops where infinite items can be bought and the money goes to the server bank account. I personally plan to use [QuickShop-Hikari](https://modrinth.com/plugin/quickshop-hikari/)

The invoice idea is great. From what I understand this will be like payment requests.

**Comment by WoofWolfGG** [comment]
Hi! POS works like a store, i.e. items are bought there (or I haven't figured it out). And in the terminal I would like to see the function of entering any amount by the seller, and when the buyer *applies* his card to the terminal, the card is charged with this amount (i.e. the same terminal that we see in regular supermarkets).

I understand about ATMs, I can't wait to try this function :)

About invoices, yes, you are right. It's just a regular invoice, like in a banking app. But I would like it to be available only for players with special permission (i.e. only government organizations can issue fines to citizens, as I have on my server)

**Comment by zefir-git** [comment]
The way POS works in BankAccounts is by setting a single-use chest with items for which the seller enters the amount. The client can right-click to review and pay. After a sale, the chest turns into a normal chest and a new POS can be set up again.

If you have something different in mind or want to suggest improvements/additions to POS, it would be great if you open a new issue for that and here in this one, we can track the invoicing feature.

**Comment by zefir-git** [comment]
Hi, currently working on this and almost ready. Just wanted some help deciding a few _admin_ permissions.

I need a permission that lets you pay an invoice not sent to you and I also need a permission to pay an invoice from account you don't own.

I can only think of `bank.invoice.pay.other` but I really think these should be 2 separate permissions.
