### ISSUE TITLE
Deposit and withdraw money

### ISSUE THREAD

**Issue by lijualun** [cloudnode-pro/BankAccounts#92]
how to deposit and withdraw money to an account . there is no command for deposit and withdraw money. only available command is set balance command. and also add some gui's.

**Comment by zefir-git** [comment]
Hi! You can also add money to an account by transferring money from the server account.

What do you mean by withdraw? If you mean creating banknotes, that will be possible with a 3rd-party plugin once we finish the vault integration in #34.

What kind of GUIs would you like to see?

**Comment by zefir-git** [comment]
I'm closing this issue as I didn't get a response. If you have additional information to add, please feel free to comment, and I can reopen the issue if necessary. For new ideas or to report bugs, kindly open a new issue. Thank you!
