### ISSUE TITLE
Automatic invoice notifications

### ISSUE THREAD

**Issue by WoofWolfGG** [cloudnode-pro/BankAccounts#95]
Hi! The new invoice system is great, thank you! 
I would like to add a small thing to it, namely - notifications about unpaid invoices every time you log in to the server (and maybe a configurable notification, e.g. once an hour)

**Comment by zefir-git** [comment]
Hi! For manual notifications, you can use `/invoice send`.

When logging in, would this be something like a "You have 123 unpaid invoices [click to view]" message?

**Comment by WoofWolfGG** [comment]
Yeah, something like that
