### ISSUE TITLE
Click-buttons issue

### ISSUE THREAD

**Issue by WoofWolfGG** [cloudnode-pro/BankAccounts#98]
![image](https://github.com/cloudnode-pro/BankAccounts/assets/77447803/165d024c-dc3c-4438-a115-0e883f669c4c)
![image](https://github.com/cloudnode-pro/BankAccounts/assets/77447803/97a662b6-a6bd-47b0-a97c-01adb66bdaac)

Hallo! All of a sudden all the clickbuttons in the plugin broke, I didn't touch anything. It happened suddenly for me. Buttons are not clickable at all, tried to put the config on the default one - the same thing. I updated PlaceholderAPI - also didn't help, so I don't know what to do

**Comment by zefir-git** [comment]
Will start working on this asap.

This issue is most likely from 1.7.0:
 - #89 
 - #90
 - #91

You can try to downgrade to [1.6.1](https://modrinth.com/plugin/bankaccounts/version/1.6.1) while I fix that. This version doesn't have invoicing though.

**Comment by zefir-git** [comment]
I've made a fix for the confirmation button (dev jar with the fix: [BankAccounts-0.0.0-SNAPSHOT.zip](https://github.com/cloudnode-pro/BankAccounts/files/14402131/BankAccounts-0.0.0-SNAPSHOT.zip)).

Will test some more to see if anything else if affected before releasing a fix in 1.7.1
